apiVersion: v1
kind: Pod
metadata:
    name: nginx-server-pod
    labels:
        app: nginx-server
        type: back-end
    namespace: nginx
spec:
    containers:
        - name: nginx-container
          image: nginx
